const urlManager = {
      login: "/login",
      register: "/register",
      createProduct: "/products",
      createMerchant: '/merchants',
      getMerchant: (id)=> `/merchants/${id}`,
      getProductByMerchantId: (id)=> `/products/merchant/${id}`,
      getAllCategories: '/categories',
      getVariantByProductId: (id)=> `/products/variant/${id}`,
      saveVariants: (id) => `/products/variant/save/${id}`,
      updateVariant: "/products/variants",
      getAllProducts: "/products",
      getDetailProduct: (id)=> `/products/${id}/details`,
      updateCart: "/cart",
      getUserById: (id)=> `/users/${id}`,
      getCartByUserId:(id)=> `/cart/user/${id}`,
      updateVariantCard: (params)=> `/cart/re-variant/${params.userId}/${params.variantCurrent}/${params.variantNew}`,
      createReview: "/reviews",
      getReviewsByProductId: (id)=> `/reviews/product/${id}`,
      getUserDetail: (id)=> `/users/${id}`,
      saveUserAddress: (userId)=> `/addresses/user/${userId}`,
      createOrder: "/orders",
      getOneVariant: (productId)=> `/products/variant/one/${productId}`,
      getShopDetails: (id)=> `/merchants/details/${id}`,
      getOrdersByShopId: `/orders/merchant`,
      getOrderById: (id)=> `/orders/${id}`,
      getOrdersByUserId: (id)=> `/orders/user/${id}`,
      getCategoriesByShop: (id)=> `/shopsections/all/${id}`,
      createShopSection: "/shopsections",
      deleteShopSection: (id)=> `/shopsections/${id}`,
      getProductsInShopSection: (id)=> `/shopsections/${id}`,
      compareCountOrderWithPreviousMonth:(id) =>`/merchants/compare-order/${id}`,
      getRevenueChart: (id)=> `/merchants/revenue-chart/${id}`,
      compareRevenueWithPreviousMonth : (id) => `/merchants/compare-revenue/${id}`,
      updateOrder : (id) => `/orders/status`,
      filterProduct: `/products/filter`,
      getVoucherById: (id) => `/vouchers/${id}`,
      createVoucher: '/vouchers',
      getVoucherByMerchant: (id)=> `/vouchers/merchants/${id}`,
      getVoucherSystem : '/vouchers/system',
      updateVoucher: (id) => `/vouchers/${id}`,
      deleteVoucher: (id) => `/vouchers/${id}`,
      getActiveVouchers: '/vouchers/active',
      getExpiredVouchers: '/vouchers/expired',
      getVoucherByCode: (code) => `/vouchers/code/${code}`,
      validateVoucher: (code) => `/vouchers/validate/${code}`,
      deactivateVoucher: (id) => `/vouchers/${id}/deactivate`,
      getVouchersByType: (type) => `/vouchers/type/${type}`,
      getVouchersByCondition: (condition) => `/vouchers/condition/${condition}`,
      getAbleVouchers: '/vouchers/able',
      getAbleVouchersByShop: '/vouchers/able/shop',
      getAbleVouchersBySystem: '/vouchers/able/system',
      addProductToWishlist: (id)=> `/wishlists/product/${id}`,
      addShopToWishlist: (id)=> `/wishlists/shop/${id}`,
      removeProductFromWishlist: (id) => `/wishlists/product/${id}`,
      removeShopFromWishlist: (id)=> `/wishlists/shop/${id}`,
      getWishlist: (id) => `/wishlists/${id}`,
      getWishlistByUserId: "/wishlists/{id}",
      getMerchantFollowers: "/wishlists/merchant",
      getAllUser: `/users`,
      getAllMerchantForm: '/form/all',
      approvalForm: '/form/approval',
      rejectForm: '/form/reject',
      getMerchantProducts: `/products/merchant`,
};

export default urlManager;
